
inte=22
stri='archana'
fl=6.1
boolean=True
compl=3+5j
lists=[1,2,3,4]
sets={1,2,3,4}
tupl=(1,2,3)
dic={"name":"archana","age":27}
res=None
print(type(inte))
print(type(stri))
print(type(fl))
print(type(boolean))
print(type(compl))
print(type(lists))
print(type(sets))
print(type(tupl))
print(type(dic))
print(type(res))
